- id: '1776560758011'
  alias: 'System: Mount GitOps Repo on Start'
  description: ''
  triggers:
  - trigger: homeassistant
    event: start
  conditions: []
  actions:
  - action: shell_command.mount_gitops_repo
    data: {}
  mode: single
- id: '1778199948893'
  alias: 'Bedroom: Media Sync Sound Machine'
  description: Turns off sound machine when Apple TV plays; turns on when it stops,
    pauses, or goes to sleep.
  triggers:
  - entity_id: media_player.master_bedroom
    to: playing
    id: tv_playing
    trigger: state
  - entity_id: media_player.master_bedroom
    from: playing
    for:
      hours: 0
      minutes: 5
      seconds: 0
    id: tv_stopped
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - tv_playing
      sequence:
      - action: switch.turn_off
        target:
          device_id: a04bbe2939204f55b7965583547aa18d
        data: {}
    - conditions:
      - condition: trigger
        id:
        - tv_stopped
      sequence:
      - action: switch.turn_on
        target:
          device_id: a04bbe2939204f55b7965583547aa18d
        data: {}
  mode: restart
- id: '1780625774998'
  alias: 'Kitchen: Overnight Night Light Motion Sync'
  description: Turns night light on (red, 75%) when motion is detected between 9:00
    PM and 6:30 AM, and turns it off 2 minutes after motion stops.
  triggers:
  - entity_id:
    - binary_sensor.smart_night_light_w_occupancy_2
    to:
    - 'on'
    id: motion_detected
    trigger: state
  - entity_id:
    - binary_sensor.smart_night_light_w_occupancy_2
    to:
    - 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
    id: motion_cleared
    trigger: state
  conditions:
  - condition: time
    after: '21:00:00'
    before: 06:30:00
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - motion_detected
      sequence:
      - action: light.turn_on
        target:
          entity_id: light.smart_night_light_w_2
        data:
          brightness_pct: 75
          rgb_color:
          - 255
          - 0
          - 0
    - conditions:
      - condition: trigger
        id:
        - motion_cleared
      sequence:
      - action: light.turn_off
        target:
          entity_id: light.smart_night_light_w_2
        data: {}
  mode: restart
- id: '1780626847173'
  alias: 'Vacation: Evening Random Light Simulator'
  description: Shuffles random labeled lights every 30 mins from 1hr before sunset
    until 10pm. Controls porch light explicitly.
  triggers:
  - minutes: /30
    id: shuffle_timer
    trigger: time_pattern
  - event: sunset
    offset: -01:00:00
    id: porch_on_time
    trigger: sun
  - at: '23:00:00'
    id: porch_off_time
    trigger: time
  conditions:
  - condition: state
    entity_id: input_select.house_mode
    state: Vacation
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: porch_on_time
      sequence:
      - action: homeassistant.turn_on
        target:
          entity_id: light.porch_light
    - conditions:
      - condition: trigger
        id: porch_off_time
      sequence:
      - action: homeassistant.turn_off
        target:
          entity_id: light.porch_light
    - conditions:
      - condition: trigger
        id: shuffle_timer
      - condition: sun
        after: sunset
        after_offset: -01:00:00
      - condition: time
        before: '22:00:00'
      sequence:
      - variables:
          all_lights: '{{ label_entities(''Lights'') | select(''match'', ''^(light|switch)\\.'')
            | reject(''eq'', ''light.porch_light'') | list }}'
          light_to_on: '{{ all_lights | random }}'
          light_to_off: '{{ all_lights | reject(''eq'', light_to_on) | list | random
            }}'
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ state_attr(light_to_on, ''supported_color_modes'')
              is not none and ''brightness'' in state_attr(light_to_on, ''supported_color_modes'')|default([])
              or state_attr(light_to_on, ''supported_features'') is not none and state_attr(light_to_on,
              ''supported_features'')|int|bitwise_and(1) > 0 }}'
          sequence:
          - action: light.turn_on
            target:
              entity_id: '{{ light_to_on }}'
            data:
              brightness_pct: 50
        - conditions: []
          sequence:
          - action: homeassistant.turn_on
            target:
              entity_id: '{{ light_to_on }}'
      - action: homeassistant.turn_off
        target:
          entity_id: '{{ light_to_off }}'
  mode: queued
- id: '1780626877331'
  alias: 'Vacation: Morning Pre-Dawn Lights'
  description: Turns on a couple of random labeled lights 1hr before sunrise (skipping
    porch) and turns them off at sunrise.
  triggers:
  - event: sunrise
    offset: -01:00:00
    id: morning_start
    trigger: sun
  - event: sunrise
    id: morning_end
    trigger: sun
  conditions:
  - condition: state
    entity_id: input_select.house_mode
    state: Vacation
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: morning_start
      sequence:
      - variables:
          all_lights: '{{ label_entities(''Lights'') | select(''match'', ''^(light|switch)\\.'')
            | reject(''eq'', ''light.porch_light'') | list }}'
          couple_lights: '{{ all_lights | shuffle | slice(0, 2) | map(attribute=0)
            | list }}'
      - repeat:
          for_each: '{{ couple_lights }}'
          sequence:
          - choose:
            - conditions:
              - condition: template
                value_template: '{{ state_attr(repeat.item, ''supported_color_modes'')
                  is not none and ''brightness'' in state_attr(repeat.item, ''supported_color_modes'')|default([])
                  or state_attr(repeat.item, ''supported_features'') is not none and
                  state_attr(repeat.item, ''supported_features'')|int|bitwise_and(1)
                  > 0 }}'
              sequence:
              - action: light.turn_on
                target:
                  entity_id: '{{ repeat.item }}'
                data:
                  brightness_pct: 50
            - conditions: []
              sequence:
              - action: homeassistant.turn_on
                target:
                  entity_id: '{{ repeat.item }}'
    - conditions:
      - condition: trigger
        id: morning_end
      sequence:
      - action: homeassistant.turn_off
        target:
          label_id: Lights
      - action: homeassistant.turn_off
        target:
          entity_id: light.porch_light
  mode: single
- id: '1780795240154'
  alias: 'Living: Daily Evening Lights'
  description: Turns on 3 specific lights 1hr before sunset and turns them off at
    9pm only if someone is home.
  triggers:
  - event: sunset
    offset: -01:00:00
    id: turn_on_time
    trigger: sun
  - at: '21:00:00'
    id: turn_off_time
    trigger: time
  conditions:
  - condition: numeric_state
    entity_id: zone.home
    above: 0
    attribute: persons
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: turn_on_time
      sequence:
      - action: homeassistant.turn_on
        target:
          entity_id:
          - light.kitchen_counter
          - light.deck_side_lamp_outlet
          - light.garden_side_lamp_outlet
        data: {}
    - conditions:
      - condition: trigger
        id: turn_off_time
      sequence:
      - action: homeassistant.turn_off
        target:
          entity_id:
          - light.living_room_lamp
          - light.kitchen_counter
          - light.hallway_light
  mode: single
- id: '1780797286761'
  alias: 'System: Automatic House Mode Sync'
  description: Manages Home, Away, and Night modes seamlessly based on time boundaries
    and zone occupancy.
  triggers:
  - entity_id: zone.home
    above: 0
    id: someone_arrived
    trigger: numeric_state
  - entity_id: zone.home
    below: 1
    id: everyone_left
    trigger: numeric_state
  - at: '21:00:00'
    id: clock_hits_9pm
    trigger: time
  - at: 06:30:00
    id: clock_hits_630am
    trigger: time
  conditions:
  - condition: template
    value_template: '{{ states(''input_select.house_mode'') != ''Vacation'' }}'
  actions:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: trigger
          id: someone_arrived
        - condition: trigger
          id: clock_hits_630am
      - condition: numeric_state
        entity_id: zone.home
        above: 0
      - condition: time
        after: 06:30:00
        before: '21:00:00'
      sequence:
      - action: input_select.select_option
        target:
          entity_id: input_select.house_mode
        data:
          option: Home
    - conditions:
      - condition: or
        conditions:
        - condition: trigger
          id: clock_hits_9pm
        - condition: trigger
          id: someone_arrived
        - condition: time
          after: '21:00:00'
          before: 06:30:00
      - condition: numeric_state
        entity_id: zone.home
        above: 0
      sequence:
      - action: input_select.select_option
        target:
          entity_id: input_select.house_mode
        data:
          option: Night
    - conditions:
      - condition: trigger
        id: everyone_left
      sequence:
      - action: input_select.select_option
        target:
          entity_id: input_select.house_mode
        data:
          option: Away
  mode: restart
