esphome:
  name: sun-porch-ac
  friendly_name: Sun Porch AC

esp32:
  board: seeed_xiao_esp32s3
  framework:
    type: esp-idf

packages:
  wifi: !include common/wifi_iot.yaml
  mitsubishi: !include packages/mitsubishi.yaml

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
